Arrays

In [1]:
from array import array

In [9]:
arr = array['i', [1, 2, 3, 4, 5]]

In [10]:
int_array = array('i', [1, 2, 3, 4, 5])

In [32]:
int_array

array('i', [1, 10, 10, 2, 4, 5, 6])

In [12]:
print(int_array[2])

3


In [13]:
int_array[2] = 30

In [14]:
int_array

array('i', [1, 2, 30, 4, 5])

In [15]:
int_array.append(6)

In [16]:
int_array.extend([7, 8, 9])

In [17]:
int_array

array('i', [1, 2, 30, 4, 5, 6, 7, 8, 9])

In [21]:
int_array.pop(-1) #last node

7

In [22]:
int_array.remove(30)

ValueError: array.remove(x): x not in array

In [24]:
int_array.insert(1, 10) #insert in position

In [25]:
int_array

array('i', [1, 10, 10, 2, 4, 5, 6])

In [26]:
int_array.count(10)

2

In [27]:
int_array.index(4)

4

In [29]:
import array as arr

In [30]:
my_array = arr.array('i', [1, 2, 3, 4, 5]) #initialize

In [31]:
my_array

array('i', [1, 2, 3, 4, 5])

In [34]:
#using numpy

In [35]:
import numpy as np

In [36]:
my_array = np.array([1, 2, 3, 4, 5])

In [37]:
my_array

array([1, 2, 3, 4, 5])

In [38]:
#Reverse

In [39]:
my_array.reverse()

AttributeError: 'numpy.ndarray' object has no attribute 'reverse'

In [40]:
int_array = [1, 2, 3, 4, 5]

In [41]:
int_array

[1, 2, 3, 4, 5]

In [42]:
int_array.reverse()

In [43]:
int_array

[5, 4, 3, 2, 1]

In [44]:
#using reversed()

In [45]:
original_list = int_array

In [46]:
original_list

[5, 4, 3, 2, 1]

In [48]:
reversed_list = reversed(original_list)

In [49]:
reversed_list

In [50]:
new_reversed_list = list(reversed_list)

In [52]:
new_reversed_list

[1, 2, 3, 4, 5]

In [53]:
original_list

[5, 4, 3, 2, 1]

In [54]:
#slicing

In [57]:
data_list = int_array

In [58]:
reversed_data = data_list[::-1]

In [59]:
data_list

[5, 4, 3, 2, 1]

In [60]:
reversed_data

[1, 2, 3, 4, 5]

In [61]:
# reversing in numpy

In [62]:
import numpy as np

In [63]:
myArray = np.array([1, 2, 3, 4, 5])

In [64]:
reversedNumpyArray = np.flip(myArray)

In [66]:
reversedNumpyArray

array([5, 4, 3, 2, 1])

In [67]:
#max and mini

In [68]:
import numpy as np

In [69]:
myArray = np.array([10, 20 ,30, 40, 50])

In [70]:
myArray.max()

np.int64(50)

In [71]:
max_element = max(myArray)

In [72]:
max_element

np.int64(50)

In [73]:
mini_element = min(myArray)

In [74]:
print(f'Mini element = {mini_element}')

Mini element = 10


In [75]:
#manual iteration

In [76]:
print(myArray)

[10 20 30 40 50]


In [85]:
myArray = np.array([10, 20, 30,40, 50, 8, 6])
if myArray.size == 0:
    print('The array is empty')
else:
    min_val = myArray[0]
    max_val = myArray[0]
    for i in myArray[1:]:
        if i < min_val:
            min_val = i
        elif i > max_val:
            max_val = i
    print(f'Minimun: {min_val}')
    print(f'Maximum: {max_val}')

Minimun: 6
Maximum: 50


In [86]:
myArray

array([10, 20, 30, 40, 50,  8,  6])

In [87]:
minNp = np.min(myArray)
maxNp = np.max(myArray)

In [88]:
print(f'Minimum: {minNp}')

Minimum: 6


In [90]:
print(f'Maximum: {maxNp}')

Maximum: 50


In [91]:
#move zeroes to end

In [95]:
def moveZeroes(nums):
    insert_pos = 0

    for i in range(len(nums)):
        if nums[i] != 0:
            nums[insert_pos] = nums[i]
            insert_pos += 1
    while insert_pos < len(nums):
        nums[insert_pos] = 0
        insert_pos += 1

arr = [0, 1, 0, 1, 10, 20, 30, 1, 2]
moveZeroes(arr)
print(arr)

[1, 1, 10, 20, 30, 1, 2, 0, 0]


In [97]:
#Matrix

In [98]:
import numpy as np

In [99]:
from numpy import *

In [111]:
A = matrix('1 2 3; 4 5 6')
B = matrix('6 5 4; 3 2 1')

In [112]:
C = A + B;

In [113]:
C

matrix([[7, 7, 7],
        [7, 7, 7]])

In [114]:
print(C)

[[7 7 7]
 [7 7 7]]


In [115]:
C = A - B

In [116]:
print(C)

[[-5 -3 -1]
 [ 1  3  5]]


In [117]:
scalar = 2.5

In [118]:
C = 2.5 * A

In [119]:
C

matrix([[ 2.5,  5. ,  7.5],
        [10. , 12.5, 15. ]])

In [120]:
print(C)

[[ 2.5  5.   7.5]
 [10.  12.5 15. ]]


In [123]:
A_transpose_1 = np.transpose(A)

In [124]:
print(A_transpose_1)

[[1 4]
 [2 5]
 [3 6]]


In [125]:
A_transpose_2 = A.T

In [126]:
print(A_transpose_2)

[[1 4]
 [2 5]
 [3 6]]
