In [1]:
import numpy as np
import pandas as pd

In [11]:
#Part A

In [12]:
A = np.array([[1, 2, 3],
             [4, 5, 6]])

B = np.array([[6, 5, 4],
             [3, 2, 1]])

In [13]:
# 1. matrix addition
addition_result = A + B

In [14]:
# 2. Matrix Subtraction
subtraction_result = A - B

In [15]:
# 3. Scalar Multiplication (multiply A by 2)
scalar_multiplication_result = A * 2

In [16]:
print('Matrix A: \n', A)
print('Matrix B: \n', B)

Matrix A: 
 [[1 2 3]
 [4 5 6]]
Matrix B: 
 [[6 5 4]
 [3 2 1]]


In [17]:
print("\nMatrix Addition (A + B):\n", addition_result)


Matrix Addition (A + B):
 [[7 7 7]
 [7 7 7]]


In [18]:
print("\nMatrix Subtraction (A - B):\n", subtraction_result)


Matrix Subtraction (A - B):
 [[-5 -3 -1]
 [ 1  3  5]]


In [19]:
print("\nScalar Multiplication (A * 2):\n", scalar_multiplication_result)


Scalar Multiplication (A * 2):
 [[ 2  4  6]
 [ 8 10 12]]


In [20]:
#partB matrix transportation

In [21]:
C = np.array([['1', '2', '3'],
             ['4', '5', '6']])

In [24]:
transpose_result = C.T

In [25]:
print("\nCharacter Matrix C:\n", C)
print("\nTransposed Character Matrix (C.T):\n", transpose_result)


Character Matrix C:
 [['1' '2' '3']
 ['4' '5' '6']]

Transposed Character Matrix (C.T):
 [['1' '4']
 ['2' '5']
 ['3' '6']]
